<?php

return [
    'name' => 'Pondok Pesantren Nurul Huda',
    'short_name' => 'Nurul Huda',
    'tagline' => 'Ilmu • Adab • Manfaat',
    'motto' => 'Membangun Generasi Qur’ani, Berilmu dan Berakhlakul Karimah',
    'address' => 'Jl. Pesantren No. 12, Lowokwaru, Malang, Jawa Timur',
    'phone' => '(0341) 555-0123',
    'whatsapp' => '0812-3456-7890',
    'email' => 'info@nurulhuda.ac.id',
    'hours' => 'Senin–Sabtu, 07.00–16.00',
    'socials' => [
        'youtube' => '#',
        'facebook' => '#',
        'instagram' => '#',
        'tiktok' => '#',
    ],
    'stats' => [
        ['value' => '20+', 'label' => 'Tahun Berdiri', 'icon' => 'building'],
        ['value' => '1.500+', 'label' => 'Santri Aktif', 'icon' => 'users'],
        ['value' => '100+', 'label' => 'Tenaga Pengajar', 'icon' => 'hat'],
        ['value' => '10.000+', 'label' => 'Alumni', 'icon' => 'badge'],
    ],
    'images' => [
        'campus' => 'images/campus.jpg',
        'mosque' => 'images/mosque.jpg',
        'students' => 'images/students.jpg',
        'classroom' => 'images/classroom.jpg',
        'library' => 'images/library.jpg',
        'quran' => 'images/quran.jpg',
        'books' => 'images/books.jpg',
        'teacher' => 'images/teacher.jpg',
        'pengasuh' => 'images/pengasuh.jpg',
        'walking' => 'images/walking.jpg',
        'sport' => 'images/sport.jpg',
        'group' => 'images/group.jpg',
        'prayer' => 'images/prayer.jpg',
        'study' => 'images/study.jpg',
        'courtyard' => 'images/courtyard.jpg',
        'lab' => 'images/lab.jpg',
        'field' => 'images/field.jpg',
        'dorm' => 'images/dorm.jpg',
    ],
];
